const CITIES = [
 {id:"shanghai",zh:"上海",en:"Shanghai",py:"SH"},{id:"beijing",zh:"北京",en:"Beijing",py:"BJ"},
 {id:"guangzhou",zh:"广州",en:"Guangzhou",py:"GZ"},{id:"shenzhen",zh:"深圳",en:"Shenzhen",py:"SZ"},
 {id:"chengdu",zh:"成都",en:"Chengdu",py:"CD"},{id:"hangzhou",zh:"杭州",en:"Hangzhou",py:"HZ"},
 {id:"nanjing",zh:"南京",en:"Nanjing",py:"NJ"},{id:"wuhan",zh:"武汉",en:"Wuhan",py:"WH"},
 {id:"xian",zh:"西安",en:"Xi'an",py:"XA"},{id:"xiamen",zh:"厦门",en:"Xiamen",py:"XM"},
 {id:"qingdao",zh:"青岛",en:"Qingdao",py:"QD"},{id:"sanya",zh:"三亚",en:"Sanya",py:"SY"}
];

const SCENES = [
 {id:"sports",emoji:"🛹",subs:["skate","tennis"],chip:"#2FD4E0"},
 {id:"music",emoji:"🎧",subs:["livehouse","techno"],chip:"#6C4DFF"},
 {id:"outdoor",emoji:"⛰️",subs:["hiking"],chip:"#A8E829"},
 {id:"shows",emoji:"🎭",subs:["comedy","musical","magic"],chip:"#FF5A36"},
 {id:"food",emoji:"🍜",subs:["dining"],chip:"#FF6FA5"},
 {id:"custom",emoji:"✨",subs:[],chip:"#FFC531"}
];

const GRADS = {
  sports:"linear-gradient(135deg,#7ee8f2,#2FD4E0)",
  music:"linear-gradient(135deg,#8b7bff,#6C4DFF)",
  outdoor:"linear-gradient(135deg,#c9f77e,#8fd435)",
  shows:"linear-gradient(135deg,#ff9d80,#FF5A36)",
  food:"linear-gradient(135deg,#ff9db5,#FF6FA5)",
  custom:"linear-gradient(135deg,#ffe08a,#FFC531)"
};

const ACTS = [
 {city:"shanghai",cat:"music",sub:"techno",emoji:"🔊",grad:"linear-gradient(135deg,#8b7bff,#6C4DFF)",d:3,hm:"22:00",price:200,going:210,spots:40,hot:true,
  zh:{t:"仓库派对 AFTERGLOW Vol.9",venue:"西岸 The Mansion",host:"AFTERGLOW",tag:"TECHNO"},
  en:{t:"Warehouse Rave: AFTERGLOW Vol.9",venue:"The Mansion, West Bund",host:"AFTERGLOW",tag:"TECHNO"},
  lineup:[["Tiehan","铁汉"],["Psyche","源识"],["Bu6b1e","泡泡"]]},
 {city:"shanghai",cat:"music",sub:"livehouse",emoji:"🎸",grad:"linear-gradient(135deg,#b09aff,#8467ff)",d:2,hm:"20:30",price:150,going:118,spots:24,hot:true,
  zh:{t:"独立摇滚之夜 · 不眠上海",venue:"育音堂公园店",host:"育音堂",tag:"LIVE"},
  en:{t:"Indie Rock Night: Sleepless SH",venue:"Yuyintang Park",host:"Yuyintang",tag:"LIVE"},
  lineup:[["Djang San","张江"],["Guests","嘉宾乐队"]]},
 {city:"shanghai",cat:"sports",sub:"skate",emoji:"🛹",grad:"linear-gradient(135deg,#7ee8f2,#2FD4E0)",d:4,hm:"18:30",price:80,going:32,spots:15,hot:false,
  zh:{t:"黄昏滑板局 · SIP 滑板公园",venue:"黄浦 SIP Skatepark",host:"沪上滑板社",tag:"SKATE"},
  en:{t:"Sunset Skate Jam @ SIP",venue:"SIP Skatepark, Huangpu",host:"SH Skaters",tag:"SKATE"},
  lineup:[["Open Session","自由滑行"],["Best Trick","大招赛"]]},
 {city:"shanghai",cat:"sports",sub:"tennis",emoji:"🎾",grad:"linear-gradient(135deg,#c9f77e,#a8e829)",d:5,hm:"10:00",price:120,going:41,spots:6,hot:false,
  zh:{t:"国际网球双打社交局",venue:"杨浦 江湾体育场",host:"沪上网球社",tag:"TENNIS"},
  en:{t:"International Tennis Mixer",venue:"Jiangwan Sports Center",host:"SH Tennis Net",tag:"TENNIS"},
  lineup:[["Doubles RR","双打循环"],["Coaching","教练陪练"]]},
 {city:"shanghai",cat:"outdoor",sub:"hiking",emoji:"⛰️",grad:"linear-gradient(135deg,#c9f77e,#8fd435)",d:11,hm:"07:30",price:180,going:88,spots:20,hot:true,
  zh:{t:"莫干山竹林徒步一日往返",venue:"浙江莫干山 · 人民广场集合",host:"山野玩家俱乐部",tag:"HIKE"},
  en:{t:"Moganshan Bamboo Forest Hike",venue:"Moganshan · meet @ People's Sq.",host:"Trailblazers CN",tag:"HIKE"},
  lineup:[["Trail A","轻松线"],["Trail B","进阶线"]]},
 {city:"shanghai",cat:"shows",sub:"comedy",emoji:"🎤",grad:"linear-gradient(135deg,#ff9d80,#FF5A36)",d:8,hm:"20:00",price:120,going:96,spots:12,hot:false,
  zh:{t:"英文脱口秀 · Kung Fu Komedy",venue:"静安 Cages",host:"KFK 喜剧",tag:"COMEDY"},
  en:{t:"Stand-up: Kung Fu Komedy",venue:"Cages, Jing'an",host:"KFK Comedy",tag:"COMEDY"},
  lineup:[["MC Alex","主持"],["3 Openers","三组开场"]]},
 {city:"shanghai",cat:"shows",sub:"musical",emoji:"🎭",grad:"linear-gradient(135deg,#ff9dc0,#FF6FA5)",d:17,hm:"19:15",price:380,going:230,spots:30,hot:true,
  zh:{t:"《悲惨世界》选段音乐会",venue:"上海大剧院",host:"SSO Live",tag:"MUSICAL"},
  en:{t:"Les Misérables Highlights in Concert",venue:"Shanghai Grand Theatre",host:"SSO Live",tag:"MUSICAL"},
  lineup:[["Orchestra","现场乐团"],["Soloists","独唱家"]]},
 {city:"shanghai",cat:"shows",sub:"magic",emoji:"🎩",grad:"linear-gradient(135deg,#ffd97e,#FFC531)",d:9,hm:"19:30",price:160,going:64,spots:18,hot:false,
  zh:{t:"近景魔术之夜 · 纸牌屋",venue:"Mansion 酒店酒廊",host:"上海魔术圈",tag:"MAGIC"},
  en:{t:"Close-up Magic: House of Cards",venue:"The Mansion lounge",host:"SH Magic Circle",tag:"MAGIC"},
  lineup:[["Card Table","纸牌桌"],["Mind Reading","读心术"]]},
 {city:"shanghai",cat:"food",sub:"dining",emoji:"🥟",grad:"linear-gradient(135deg,#ff9db5,#FF6FA5)",d:4,hm:"17:00",price:98,going:27,spots:10,hot:false,
  zh:{t:"包饺子社交晚餐",venue:"黄浦 老码头",host:"寻味上海",tag:"FOOD"},
  en:{t:"Dumpling Making Social Dinner",venue:"Cool Docks, Huangpu",host:"Taste of SH",tag:"FOOD"},
  lineup:[["DIY Table","动手桌"],["Sauce Lab","蘸料实验室"]]},
 {city:"shanghai",cat:"food",sub:"dining",emoji:"🍲",grad:"linear-gradient(135deg,#ffb08a,#ff7a45)",d:5,hm:"18:30",price:128,going:19,spots:8,hot:false,
  zh:{t:"川味火锅之夜 🔥",venue:"人民广场 海底捞",host:"嗜辣星人",tag:"HOTPOT"},
  en:{t:"Spicy Sichuan Hotpot Night 🔥",venue:"Haidilao, People's Sq.",host:"Chili Heads SH",tag:"HOTPOT"},
  lineup:[["Mild Table","微辣桌"],["Hell Table","地狱辣桌"]]},
 {city:"beijing",cat:"music",sub:"techno",emoji:"🔊",grad:"linear-gradient(135deg,#8b7bff,#6C4DFF)",d:4,hm:"22:00",price:180,going:185,spots:35,hot:true,
  zh:{t:"地下 House 之夜 · 鼓楼律动",venue:"鼓楼 朝阳洞酒吧",host:"Gulou Grooves",tag:"HOUSE"},
  en:{t:"Underground House: Gulou Grooves",venue:"Zhaoyang Cave, Gulou",host:"Gulou Grooves",tag:"HOUSE"},
  lineup:[["Viene","律动使者"],["Ting","联觉治疗师"],["Jay D","声音构筑师"]]},
 {city:"beijing",cat:"music",sub:"livehouse",emoji:"🎸",grad:"linear-gradient(135deg,#b09aff,#8467ff)",d:2,hm:"21:00",price:180,going:140,spots:30,hot:false,
  zh:{t:"后摇现场 · Djang San 及嘉宾",venue:"五道营 School Bar",host:"School Bar",tag:"LIVE"},
  en:{t:"Post-Rock Live: Djang San + Guests",venue:"School Bar, Wudaoying",host:"School Bar",tag:"LIVE"},
  lineup:[["Djang San","张江"],["Guest Band","嘉宾"]]},
 {city:"beijing",cat:"outdoor",sub:"hiking",emoji:"🍁",grad:"linear-gradient(135deg,#ffd97e,#ffa53d)",d:11,hm:"07:00",price:150,going:102,spots:25,hot:true,
  zh:{t:"慕田峪长城金秋徒步",venue:"慕田峪 · 东直门集合",host:"北京行山团",tag:"HIKE"},
  en:{t:"Mutianyu Great Wall Autumn Hike",venue:"Mutianyu · meet @ Dongzhimen",host:"Hike & Seek BJ",tag:"HIKE"},
  lineup:[["Cable Car","缆车组"],["Full Trail","全程徒步组"]]},
 {city:"beijing",cat:"shows",sub:"comedy",emoji:"🎤",grad:"linear-gradient(135deg,#ff9d80,#FF5A36)",d:7,hm:"20:00",price:150,going:88,spots:14,hot:false,
  zh:{t:"双语脱口秀 · 北京人儿",venue:"三里屯 老书虫",host:"Comedy Club CN",tag:"COMEDY"},
  en:{t:"Bilingual Comedy: The Beijingers",venue:"The Bookworm, Sanlitun",host:"Comedy Club CN",tag:"COMEDY"},
  lineup:[["EN Set","英文组"],["CN Set","中文组"]]},
 {city:"beijing",cat:"food",sub:"dining",emoji:"🦆",grad:"linear-gradient(135deg,#ffb08a,#ff7a45)",d:4,hm:"18:00",price:158,going:31,spots:12,hot:false,
  zh:{t:"烤鸭晚餐 + 胡同漫步",venue:"西城 四合瓦院",host:"老北京味道",tag:"FOOD"},
  en:{t:"Peking Duck Dinner + Hutong Walk",venue:"Sihewan, Xicheng",host:"Old BJ Bites",tag:"FOOD"},
  lineup:[["Roast Table","烤鸭桌"],["Hutong Tour","胡同导览"]]},
 {city:"beijing",cat:"sports",sub:"skate",emoji:"🛹",grad:"linear-gradient(135deg,#7ee8f2,#2FD4E0)",d:11,hm:"09:00",price:70,going:25,spots:18,hot:false,
  zh:{t:"长城滑板之旅 + 烧烤",venue:"黄花城水长城",host:"北京滑板小队",tag:"SKATE"},
  en:{t:"Great Wall Skate Trip + BBQ",venue:"Huanghuacheng",host:"BJ Skate Crew",tag:"SKATE"},
  lineup:[["Skate Park","板场"],["BBQ Pit","烧烤"]]},
 {city:"beijing",cat:"sports",sub:"tennis",emoji:"🎾",grad:"linear-gradient(135deg,#c9f77e,#a8e829)",d:5,hm:"09:00",price:100,going:33,spots:8,hot:false,
  zh:{t:"朝阳周日网球社交局",venue:"朝阳体育中心",host:"京城球友会",tag:"TENNIS"},
  en:{t:"Sunday Tennis Social · Chaoyang",venue:"Chaoyang Sports Park",host:"BJ Tennis Buddies",tag:"TENNIS"},
  lineup:[["Round Robin","循环赛"]]},
 {city:"chengdu",cat:"music",sub:"livehouse",emoji:"🎸",grad:"linear-gradient(135deg,#b09aff,#8467ff)",d:2,hm:"20:00",price:140,going:95,spots:26,hot:true,
  zh:{t:"成都独立音乐夜 @ NUSPACE",venue:"玉林 NUSPACE",host:"NUSPACE",tag:"LIVE"},
  en:{t:"Chengdu Indie Night @ NUSPACE",venue:"NUSPACE, Yulin",host:"NUSPACE",tag:"LIVE"},
  lineup:[["Local Heroes","本地英雄"],["Guest","嘉宾"]]},
 {city:"chengdu",cat:"food",sub:"dining",emoji:"🌶️",grad:"linear-gradient(135deg,#ff9d80,#FF5A36)",d:4,hm:"18:00",price:88,going:24,spots:10,hot:true,
  zh:{t:"成都街头小吃扫街局",venue:"建设路夜市",host:"成都吃货团",tag:"FOOD"},
  en:{t:"Sichuan Street Food Crawl",venue:"Jianshe Rd Night Market",host:"CDO Foodies",tag:"FOOD"},
  lineup:[["6 Stops","六站打卡"]]},
 {city:"chengdu",cat:"outdoor",sub:"hiking",emoji:"🐼",grad:"linear-gradient(135deg,#c9f77e,#8fd435)",d:5,hm:"07:30",price:160,going:76,spots:22,hot:false,
  zh:{t:"青城山徒步洗肺之旅",venue:"青城山 · 成都东站集合",host:"熊猫步道俱乐部",tag:"HIKE"},
  en:{t:"Mount Qingcheng Nature Hike",venue:"Qingchengshan · East Stn.",host:"Panda Trails",tag:"HIKE"},
  lineup:[["Front Mtn.","前山"],["Back Mtn.","后山"]]},
 {city:"chengdu",cat:"sports",sub:"skate",emoji:"🛹",grad:"linear-gradient(135deg,#7ee8f2,#2FD4E0)",d:4,hm:"16:00",price:60,going:28,spots:16,hot:false,
  zh:{t:"成都滑板聚会 · 新浪公园",venue:"高新 新浪滑板公园",host:"CD 滑板社",tag:"SKATE"},
  en:{t:"Chengdu Skate Meet @ New Wave",venue:"New Wave Park, Gaoxin",host:"CD Skate Fam",tag:"SKATE"},
  lineup:[["Open Session","自由滑行"]]},
 {city:"shenzhen",cat:"music",sub:"techno",emoji:"🔊",grad:"linear-gradient(135deg,#8b7bff,#6C4DFF)",d:4,hm:"21:00",price:190,going:160,spots:30,hot:true,
  zh:{t:"天台 Techno · 华侨城创意园",venue:"南山 华侨城创意园",host:"SZ Underground",tag:"TECHNO"},
  en:{t:"Rooftop Techno: OCT-Loft",venue:"OCT-Loft, Nanshan",host:"SZ Underground",tag:"TECHNO"},
  lineup:[["Terrace","天台"],["Warehouse","仓库"]]},
 {city:"shenzhen",cat:"outdoor",sub:"hiking",emoji:"🌊",grad:"linear-gradient(135deg,#7ee8f2,#2FD4E0)",d:5,hm:"08:00",price:140,going:81,spots:24,hot:false,
  zh:{t:"东涌海岸线徒步",venue:"大鹏半岛 · 车公庙集合",host:"深圳徒盟",tag:"HIKE"},
  en:{t:"Dongchong Coastal Trail Hike",venue:"Dapeng · Chegongmiao meet",host:"SZ Hikers",tag:"HIKE"},
  lineup:[["Coast Line","海岸线"],["Beach End","沙滩终点"]]},
 {city:"shenzhen",cat:"sports",sub:"tennis",emoji:"🎾",grad:"linear-gradient(135deg,#c9f77e,#a8e829)",d:4,hm:"09:30",price:110,going:29,spots:9,hot:false,
  zh:{t:"深圳湾网球社交局",venue:"深圳湾体育中心",host:"深网球友会",tag:"TENNIS"},
  en:{t:"Shenzhen Bay Tennis Social",venue:"SZ Bay Sports Center",host:"SZ Tennis Meetup",tag:"TENNIS"},
  lineup:[["Sea View Courts","海景球场"]]},
 {city:"guangzhou",cat:"food",sub:"dining",emoji:"🍵",grad:"linear-gradient(135deg,#c9f77e,#8fd435)",d:5,hm:"10:30",price:108,going:26,spots:12,hot:true,
  zh:{t:"广式早茶午宴 + 珠江漫步",venue:"荔湾 广州酒家",host:"食在广州",tag:"DIM SUM"},
  en:{t:"Cantonese Dim Sum + Pearl River Walk",venue:"Guangzhou Restaurant, Liwan",host:"Canton Bites",tag:"DIM SUM"},
  lineup:[["Morning Tea","早茶桌"]]},
 {city:"guangzhou",cat:"shows",sub:"musical",emoji:"🎭",grad:"linear-gradient(135deg,#ff9dc0,#FF6FA5)",d:17,hm:"19:30",price:320,going:150,spots:28,hot:false,
  zh:{t:"音乐剧《猫》广州巡演",venue:"广州大剧院",host:"GH 音乐剧",tag:"MUSICAL"},
  en:{t:"Musical: CATS Guangzhou Tour",venue:"Guangzhou Opera House",host:"GH Musical",tag:"MUSICAL"},
  lineup:[["World Tour Cast","巡演卡司"]]},
 {city:"guangzhou",cat:"music",sub:"livehouse",emoji:"🎸",grad:"linear-gradient(135deg,#b09aff,#8467ff)",d:2,hm:"20:30",price:130,going:87,spots:22,hot:false,
  zh:{t:"粤语摇滚之夜 @ SD Livehouse",venue:"海珠 SD Livehouse",host:"SD Live",tag:"LIVE"},
  en:{t:"Canton Rock Night @ SD",venue:"SD Livehouse, Haizhu",host:"SD Live",tag:"LIVE"},
  lineup:[["3 Bands","三支乐队"]]},
 {city:"hangzhou",cat:"outdoor",sub:"hiking",emoji:"🚣",grad:"linear-gradient(135deg,#c9f77e,#8fd435)",d:11,hm:"06:00",price:170,going:92,spots:20,hot:true,
  zh:{t:"西湖日出徒步 + 船上早午餐",venue:"北高峰 · 西湖",host:"杭州户外实验室",tag:"HIKE"},
  en:{t:"West Lake Sunrise + Boat Brunch",venue:"Beigaofeng · West Lake",host:"HZ Outdoor Lab",tag:"HIKE"},
  lineup:[["Sunrise Group","日出组"],["Boat Brunch","游船早午餐"]]},
 {city:"hangzhou",cat:"music",sub:"techno",emoji:"🔊",grad:"linear-gradient(135deg,#8b7bff,#6C4DFF)",d:11,hm:"15:00",price:160,going:98,spots:26,hot:false,
  zh:{t:"湖畔 House 派对 · 千岛湖站",venue:"千岛湖 · 杭州东站集合",host:"西湖律动",tag:"HOUSE"},
  en:{t:"Lakeside House: Qiandao Edition",venue:"Qiandao Lake · East Stn.",host:"West Lake Groove",tag:"HOUSE"},
  lineup:[["Day Stage","日间舞台"],["Sunset Set","日落场"]]},
 {city:"xiamen",cat:"outdoor",sub:"hiking",emoji:"🏝️",grad:"linear-gradient(135deg,#7ee8f2,#2FD4E0)",d:11,hm:"08:30",price:150,going:47,spots:18,hot:false,
  zh:{t:"厦门环岛骑行 + 海岸徒步",venue:"环岛路 · 厦门",host:"厦门海岛社",tag:"BIKE+HIKE"},
  en:{t:"Xiamen Coastal Cycling + Hike",venue:"Huandao Rd, Xiamen",host:"XM Island Club",tag:"BIKE+HIKE"},
  lineup:[["Cruise Ride","休闲骑"],["Fast Peloton","竞速组"]]},
 {city:"sanya",cat:"outdoor",sub:"hiking",emoji:"🌴",grad:"linear-gradient(135deg,#ffd97e,#ffa53d)",d:12,hm:"08:00",price:200,going:38,spots:16,hot:false,
  zh:{t:"三亚浮潜 + 雨林穿越",venue:"蜈支洲岛 · 三亚",host:"山海三亚",tag:"WATER"},
  en:{t:"Sanya Snorkeling + Rainforest Trek",venue:"Wuzhizhou Island",host:"Sanya Sea&Trail",tag:"WATER"},
  lineup:[["Snorkel","浮潜组"],["Jungle","丛林组"]]},
 {city:"xian",cat:"shows",sub:"magic",emoji:"🎩",grad:"linear-gradient(135deg,#ffd97e,#FFC531)",d:11,hm:"19:00",price:130,going:52,spots:20,hot:false,
  zh:{t:"大唐魔术晚宴秀",venue:"大唐不夜城 · 西安",host:"长安夜宴",tag:"MAGIC"},
  en:{t:"Tang Dynasty Magic Dinner Show",venue:"Datang Everbright City",host:"Chang'an Nights",tag:"MAGIC"},
  lineup:[["Stage Magic","舞台魔术"],["Close-up","近景魔术"]]},
 {city:"wuhan",cat:"sports",sub:"skate",emoji:"🛹",grad:"linear-gradient(135deg,#7ee8f2,#2FD4E0)",d:4,hm:"17:00",price:60,going:22,spots:14,hot:false,
  zh:{t:"武汉江滩滑板局",venue:"汉口江滩公园",host:"武汉滑板社",tag:"SKATE"},
  en:{t:"Wuhan Riverside Skate Session",venue:"Hankou Jiangtan Park",host:"WH Skate",tag:"SKATE"},
  lineup:[["Open Session","自由滑行"]]},
 {city:"nanjing",cat:"shows",sub:"comedy",emoji:"🎤",grad:"linear-gradient(135deg,#ff9d80,#FF5A36)",d:9,hm:"20:00",price:110,going:60,spots:15,hot:false,
  zh:{t:"南京英文脱口秀之夜",venue:"玄武 1912 街区",host:"NJ Laughs",tag:"COMEDY"},
  en:{t:"English Comedy Night Nanjing",venue:"1912 Bar St, Xuanwu",host:"NJ Laughs",tag:"COMEDY"},
  lineup:[["Open Mic","开放麦"]]},
 {city:"qingdao",cat:"food",sub:"dining",emoji:"🍺",grad:"linear-gradient(135deg,#ffb08a,#ff7a45)",d:4,hm:"18:30",price:118,going:35,spots:14,hot:false,
  zh:{t:"青岛啤酒 + 海鲜大餐",venue:"市南 劈柴院",host:"青岛吃喝团",tag:"BEER"},
  en:{t:"Tsingtao Beer & Seafood Feast",venue:"Pichaiyuan, Shinan",host:"QD Eats & Ales",tag:"BEER"},
  lineup:[["Beer Garden","啤酒花园"]]},
 {city:"shanghai",cat:"custom",sub:"custom",emoji:"🎲",grad:"linear-gradient(135deg,#ffe08a,#FFC531)",d:5,hm:"19:30",price:80,going:26,spots:10,hot:false,
  zh:{t:"桌游 & 剧本杀之夜",venue:"静安 Board Game Bar",host:"Dice & Chill",tag:"BOARD GAMES"},
  en:{t:"Board Games & Script Murder Night",venue:"Board Game Bar, Jing'an",host:"Dice & Chill",tag:"BOARD GAMES"},
  lineup:[["Werewolf","狼人杀"],["Script","剧本杀"]]},
 {city:"beijing",cat:"custom",sub:"custom",emoji:"💬",grad:"linear-gradient(135deg,#ffd76e,#f5a623)",d:2,hm:"15:00",price:50,going:41,spots:15,hot:false,
  zh:{t:"中英语言交换下午茶",venue:"朝阳 The Corner Café",host:"Mandarin Mates",tag:"LANGUAGE EXCHANGE"},
  en:{t:"CN-EN Language Exchange Tea",venue:"The Corner Café, Chaoyang",host:"Mandarin Mates",tag:"LANGUAGE EXCHANGE"},
  lineup:[["Free Talk","自由聊"],["Games","破冰游戏"]]}
];

const I18N = {
 zh:{
  langBtn:"EN",tSearch:"搜索：演示占位 ✦",searchPh:"搜活动 / 场地 / 艺人 / 搭子…",
  all:"全部",viewAll:"全部 →",inCity:"",
  listTitle:"全部活动",sceneName:{sports:"运动 SPORTS",music:"音乐 MUSIC",outdoor:"游玩 OUTDOOR",shows:"表演 SHOWS",food:"美食 FOOD",custom:"自定义 OTHERS"},
  sceneShort:{sports:"运动",music:"音乐",outdoor:"游玩",shows:"表演",food:"美食",custom:"自定义"},
  subs:{all:"全部",skate:"滑板",tennis:"网球",livehouse:"Live House",techno:"Techno/House",hiking:"游山玩水",comedy:"脱口秀",musical:"音乐剧",magic:"魔术",dining:"聚餐"},
  statDesc:"本周活动开票中",statTix:"我的票夹 · 出示入场",
  people:"人已加入",left:"余票",per:"/人",
  railTitle:"本周热榜",soonTitle:"马上开跳",
  lineup:"阵容 LINE-UP",who:"谁会来",joinGroup:"加入活动群 · 找搭子",
  dLabels:{date:"日期时间",venue:"场地",host:"主办方",tix:"票务",lang:"语言"},
  tixTypes:{early:"早鸟票",pre:"预售票",door:"现场票"},
  tixDesc:{early:"限量发售 · 售完即止",pre:"开场前在线购",door:"现场排队 · 数量有限"},
  buy:"立即购票",bought:"已购票 ✓",buyOk:"🎫 购票成功！已放入票夹",cancelOk:"已取消",
  selling:"售票中",
  calBrand:"日历",tixBrand:"票夹",
  weekday:["周日","周一","周二","周三","周四","周五","周六"],
  emptyTix:"还没有票<br>去发现页逛逛 ✦",emptyCal:"这一天空空如也",
  meName:"Alex Chen",stJ:"参加过",stF:"收藏",stR:"评价",stH:"发起",
  meSub:"📍 上海 · 🇺🇸 EN · 12 场活动记录",
  meMenu:[["🎟️","我的报名","booked"],["⭐","收藏的活动","fav"],["🔔","开票提醒","notif"],["🌍","语言设置","lang"],["🎧","帮助与客服","help"]],
  meToast:{booked:"🎟️ 查看我的报名",fav:"⭐ 查看收藏",notif:"🔔 提醒设置（演示）",lang:"🌍 EN / 中文",help:"🎧 微信客服：LarkyGO-Support"},
  sheetCityT:"换个城市开玩 🌏",
  pickCityOk:"去 ",tixStatus:{valid:"有效",used:"已核销"},ticketNo:"NO.",
  shareOk:"🔗 链接已复制",joinOk:"💬 已加入活动群",
  emptyCity:"这座城市还没活动 · 期待发起人 ✦",emptySub:"该场景暂无活动",
  heroSceneTxt:"热榜 TOP 1",
  /* --- AI chat --- */
  chatSub:"聊天找活动 · 发活动 · 传海报",
  chatPh:"问我活动，或说「发布活动」…",
  chatWelcome:"嗨，我是 LarkyGO AI ✦\n想玩点什么？我可以：\n\n🔍 直接问我——「本周有什么音乐活动」「北京有什么徒步」\n✦ 说「我要发布活动」，一步步帮你创建\n📷 点下方相机上传海报，我自动识别信息发布",
  chatChips:["本周有什么活动？","推荐音乐活动","我要发布活动","上海有什么脱口秀？"],
  chatFound:"帮你找到 {n} 场活动：",
  chatNotFound:"这波没搜到 😅\n换个说法试试？比如「音乐」「徒步」「脱口秀」「火锅」",
  chatGoAll:"看全部活动 →",
  chatPubStart:"好嘞！发起活动 🎉\n先说说——活动叫什么名字？",
  chatPubScene:"收到「{t}」✦\n属于哪个场景？运动 / 音乐 / 游玩 / 表演 / 美食\n💡 不属于这些？直接输入你的自定义类别（如「桌游」「市集」「观影」）",
  chatPubCustom:"没问题！已创建自定义类别「{t}」✨\n活动什么时间举办？",
  chatPubNameGen:"包在我身上 ✨ 就叫「{t}」！\n属于哪个场景？运动 / 音乐 / 游玩 / 表演 / 美食\n💡 不属于这些？直接输入你的自定义类别（如「桌游」「市集」「观影」）",
  chatPubSceneAny:"帮你抽一个 ✨「{t}」！\n活动什么时间举办？",
  chatPubWhenAny:"没问题，先记「{t}」，回头可改 ✦\n场地在哪里？（带上城市更好，如「上海 静安寺」）",
  chatPubSceneRetry:"没认出来 🤔 再说一次？\n运动 / 音乐 / 游玩 / 表演 / 美食",
  chatPubWhen:"时间定在什么时候？\n（比如：10月12日 周六 20:00）",
  chatPubVenue:"场地在哪？\n（比如：上海 育音堂公园店）",
  chatPubPrice:"票价多少？直接说数字就行～\n（比如：120）",
  chatPubCancel:"已退出发布 ✦ 随时再喊我",
  chatPubDone:"🎉 发布成功！已经出现在「发现」页热榜里，票种帮你配好早鸟/预售/现场三档。",
  chatImgAsk:"把海报发给我就行 📷\n点输入框左边的相机按钮～",
  chatImgRead:"识图完成 ✨ 从海报里读出了这些信息：",
  chatImgOk:"确认发布",
  chatImgRedo:"换一张",
  chatDraftTitle:"✦ 识别结果",
  chatPubSummary:"最后确认一下信息：",
  chatYouHost:"你（发起人）"
 },
 en:{
  langBtn:"中",tSearch:"Search: demo placeholder ✦",searchPh:"Search events / venues / artists / crew…",
  all:"All",viewAll:"All →",inCity:"in",
  listTitle:"All Events",sceneName:{sports:"SPORTS",music:"MUSIC",outdoor:"OUTDOOR",shows:"SHOWS",food:"FOOD",custom:"OTHERS"},
  sceneShort:{sports:"Sports",music:"Music",outdoor:"Outdoor",shows:"Shows",food:"Food",custom:"Others"},
  subs:{all:"All",skate:"Skateboarding",tennis:"Tennis",livehouse:"Live House",techno:"Techno/House",hiking:"Hiking & Nature",comedy:"Stand-up",musical:"Musicals",magic:"Magic",dining:"Dining"},
  statDesc:"events on sale this week",statTix:"My tickets · show to enter",
  people:"going",left:"left",per:"/pp",
  railTitle:"This Week's <u>HOT</u>",soonTitle:"Starting <em>Soon</em>",
  lineup:"LINE-UP",who:"Who's in",joinGroup:"Join group chat & find your crew",
  dLabels:{date:"Date & Time",venue:"Venue",host:"Host",tix:"Tickets",lang:"Language"},
  tixTypes:{early:"EARLY BIRD",pre:"PRESALE",door:"AT DOOR"},
  tixDesc:{early:"Limited · while stocks last",pre:"Online · before doors",door:"Walk-up · very limited"},
  buy:"GET TICKET",bought:"TICKETED ✓",buyOk:"🎫 Booked! Saved to wallet",cancelOk:"Cancelled",
  selling:"ON SALE",
  calBrand:"Calendar",tixBrand:"Tickets",
  weekday:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],
  emptyTix:"No tickets yet<br>go explore ✦",emptyCal:"Nothing on this day",
  meName:"Alex Chen",stJ:"Joined",stF:"Saved",stR:"Reviews",stH:"Hosted",
  meSub:"📍 Shanghai · 🇺🇸 · 12 events attended",
  meMenu:[["🎟️","My Bookings","booked"],["⭐","Saved Events","fav"],["🔔","Sale Alerts","notif"],["🌍","Language","lang"],["🎧","Help & Support","help"]],
  meToast:{booked:"🎟️ My bookings",fav:"⭐ Saved events",notif:"🔔 Alerts (demo)",lang:"🌍 EN / 中文",help:"🎧 WeChat: LarkyGO-Support"},
  sheetCityT:"Pick a city 🌏",
  pickCityOk:"Now in ",tixStatus:{valid:"VALID",used:"USED"},ticketNo:"NO.",
  shareOk:"🔗 Link copied",joinOk:"💬 Joined group chat",
  emptyCity:"No events here yet · be the host ✦",emptySub:"Nothing in this scene yet",
  heroSceneTxt:"TOP PICK",
  /* --- AI chat --- */
  chatSub:"Chat to find & host events",
  chatPh:"Ask me anything, or say \"host an event\"…",
  chatWelcome:"Hey, I'm LarkyGO AI ✦\nWhat are you up for?\n\n🔍 Ask me — \"music events this week\", \"hiking in Beijing\"\n✦ Say \"I want to host\" and I'll guide you step by step\n📷 Tap the camera below, upload a poster — I'll extract everything",
  chatChips:["Events this week?","Recommend music events","I want to host an event","Any comedy in Shanghai?"],
  chatFound:"Found {n} events for you:",
  chatNotFound:"Nothing matched 😅\nTry \"music\", \"hiking\", \"comedy\", \"hotpot\"…",
  chatGoAll:"See all events →",
  chatPubStart:"Let's do it! 🎉\nFirst — what's the event called?",
  chatPubScene:"Got it: \"{t}\" ✦\nWhich scene? Sports / Music / Outdoor / Shows / Food\n💡 None of these? Just type your own category (e.g. \"Board Games\", \"Market\", \"Cinema\")",
  chatPubCustom:"Cool! Custom category \"{t}\" created ✨\nWhen does it happen?",
  chatPubNameGen:"Leave it to me ✨ Let's call it \"{t}\"!\nWhich scene? Sports / Music / Outdoor / Shows / Food\n💡 None of these? Just type your own category (e.g. \"Board Games\", \"Market\", \"Cinema\")",
  chatPubSceneAny:"I'll pick one for you ✨ \"{t}\"!\nWhen does it happen?",
  chatPubWhenAny:"Sure, pencilled in as \"{t}\" — editable later ✦\nWhere's the venue? (add the city, e.g. \"Jing'an, Shanghai\")",
  chatPubSceneRetry:"Didn't catch that 🤔 One more time?\nSports / Music / Outdoor / Shows / Food",
  chatPubWhen:"When is it?\n(e.g. Oct 12, Sat, 20:00)",
  chatPubVenue:"Where's the venue?\n(e.g. Yuyintang Park, Shanghai)",
  chatPubPrice:"Ticket price? Just a number~\n(e.g. 120)",
  chatPubCancel:"Exited hosting ✦ Ping me anytime",
  chatPubDone:"🎉 Published! It's live on Discover — I've set up Early/Presale/Door tiers for you.",
  chatImgAsk:"Just send me the poster 📷\nTap the camera button next to the input~",
  chatImgRead:"Scan complete ✨ Here's what I read from the poster:",
  chatImgOk:"PUBLISH",
  chatImgRedo:"Try another",
  chatDraftTitle:"✦ EXTRACTED",
  chatPubSummary:"Quick final check:",
  chatYouHost:"You (host)"
 }
};

const SUB_KW = {skate:["滑板","skate"],tennis:["网球","tennis"],livehouse:["livehouse","live house","乐队","现场演出"],techno:["techno","house","电子","rave","派对","dj","蹦迪"],hiking:["徒步","爬山","hike","露营","骑行","游山玩水"],comedy:["脱口秀","喜剧","comedy","段子","开放麦"],musical:["音乐剧","musical"],magic:["魔术","magic"],dining:["聚餐","火锅","美食","dinner","food","吃饭","小吃","早茶"]};

const SCENE_KW = {sports:["运动","sport","滑板","网球"],music:["音乐","music","live","演出"],outdoor:["游玩","户外","outdoor","山","海"],shows:["表演","show","脱口秀","音乐剧","魔术"],food:["吃","美食","food"],custom:["自定义","custom","other","桌游","市集","剧本杀","language exchange","语言交换","观影","board game"]};

module.exports = { CITIES, SCENES, GRADS, ACTS, I18N, SUB_KW, SCENE_KW };
